languageCode = "en"
languageName = "English"
weight = 1
title = "Strings And Tines"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "llamalogo_icon.png"
secondaryLogo = "llamalogo_whitegray.png"
description = "A collection of my instruments, musical creations, and other projects."

# Commented this out since it was showing up on the front page as the title of the page
#[author]
#name = "Alex Llama"
