[[main]]
none = "none"

###### Instruments ######

[[main]]
name = "Instruments"
pageRef = "instruments"
url = "/Instruments/"
identifier = "WaoMVczQl5"
weight = 1

[[main]]
name = "Guitars"
pageRef = "guitars"
identifier = "guitars"
url = "/Instruments/Guitars/"
parent = "WaoMVczQl5"
weight = 1

[[main]]
name = "Kalimbas"
pageRef = "kalimbas"
identifier = "kalimbas"
url = "/Instruments/Kalimbas/"
parent = "WaoMVczQl5"
weight = 2

[[main]]
name = "Dulcimers"
pageRef = "dulcimers"
identifier = "dulcimers"
url = "/Instruments/Dulcimers/"
parent = "WaoMVczQl5"
weight = 3

[[main]]
name = "Hand Pans"
pageRef = "handpans"
identifier = "handpans"
url = "/Instruments/HandPans/"
parent = "WaoMVczQl5"
weight = 4

[[main]]
name = "World"
pageRef = "world"
identifier = "world"
url = "/Instruments/World/"
parent = "WaoMVczQl5"
weight = 5

[[main]]
name = "Ukuleles"
pageRef = "ukuleles"
identifier = "ukuleles"
url = "/Instruments/Ukuleles/"
parent = "WaoMVczQl5"
weight = 6

[[main]]
name = "Diddley Bows"
pageRef = "diddleybows"
identifier = "diddleybows"
url = "/Instruments/DiddleyBows/"
parent = "WaoMVczQl5"
weight = 7

[[main]]
name = "Canjos"
pageRef = "canjos"
identifier = "canjos"
url = "/Instruments/Canjos/"
parent = "WaoMVczQl5"
weight = 8

[[main]]
name = "Harps"
pageRef = "harps"
identifier = "harps"
url = "/Instruments/Harps/"
parent = "WaoMVczQl5"
weight = 9

[[main]]
name = "Misc Instruments"
pageRef = "miscinstruments"
identifier = "miscinstruments"
url = "/Instruments/MiscInstruments/"
parent = "WaoMVczQl5"
weight = 10

###### Gear ######

[[main]]
name = "Gear"
pageRef = "gear"
url = "/Gear/"
identifier = "kNkZxyimtI"
weight = 2

[[main]]
name = "Amps"
pageRef = "amps"
identifier = "amps"
url = "/Gear/Amps/"
parent = "kNkZxyimtI"
weight = 1

[[main]]
name = "Pedals"
pageRef = "pedals"
identifier = "pedals"
url = "/Gear/Pedals/"
parent = "kNkZxyimtI"
weight = 2

[[main]]
name = "Mics"
pageRef = "mics"
identifier = "mics"
url = "/Gear/Mics/"
parent = "kNkZxyimtI"
weight = 3

[[main]]
name = "Slides"
pageRef = "slides"
identifier = "slides"
url = "/Gear/Slides/"
parent = "kNkZxyimtI"
weight = 4

[[main]]
name = "Speakers"
pageRef = "speakers"
identifier = "speakers"
url = "/Gear/Speakers/"
parent = "kNkZxyimtI"
weight = 5

###### Electronics ######

[[main]]
name = "Electronics"
pageRef = "Electronics"
url = "/Electronics/"
identifier = "suyRDlkuyR"
weight = 4

###### Photography ######

[[main]]
name = "Photography"
pageRef = "photography"
url = "/Photography/"
identifier = "uyffYFTUoh"
weight = 5

###### Woodworking ######

[[main]]
name = "Woodworking"
pageRef = "woodworking"
url = "/Woodworking/"
identifier = "qrafsgdurj"
weight = 6

###### Apparel ######

[[main]]
name = "Apparel"
pageRef = "Apparel"
url = "/Apparel/"
identifier = "hfrYNBGFeT"
weight = 7

[[main]]
name = "Watch Mods"
pageRef = "watchmods"
identifier = "watchmods"
url = "/Apparel/Watch Mods/"
parent = "hfrYNBGFeT"
weight = 1

[[main]]
name = "Shirts"
pageRef = "shirts"
identifier = "shirts"
url = "/Apparel/Shirts/"
parent = "hfrYNBGFeT"
weight = 2

###### Code ######

[[main]]
name = "Code"
pageRef = "Code"
url = "/Code/"
identifier = "kiUHedGdcY"
weight = 8

[[main]]
name = "Cornhole Score Tracker"
pageRef = "cornhole"
identifier = "cornhole"
url = "/Code/Cornhole/"
parent = "kiUHedGdcY"
weight = 1

[[main]]
name = "Volleyball Stats Tracker"
pageRef = "volleyballstatstracker"
identifier = "volleyballstatstracker"
url = "/Code/VolleyballStatsTracker/"
parent = "kiUHedGdcY"
weight = 2

[[main]]
name = "Weather Hologram"
pageRef = "weatherhologram"
identifier = "weatherhologram"
url = "/Apparel/WeatherHologram/"
parent = "kiUHedGdcY"
weight = 3

###### Footer ######

[[footer]]
none = "none"

[[footer]]
name = "Home"
pageRef = ""
identifier = "b0M0hadtTb"
weight = 9999
