[[main]]
none = "none"

###### Instruments ######

[[main]]
name = "Instruments"
pageRef = "instruments"
url = "/instruments"
identifier = "WaoMVczQl5"
weight = 1

[[main]]
name = "Guitars"
pageRef = "guitars"
identifier = "guitars"
url = "/instruments/guitars"
parent = "WaoMVczQl5"
weight = 1

[[main]]
name = "Kalimbas"
pageRef = "kalimbas"
identifier = "kalimbas"
url = "/instruments/kalimbas"
parent = "WaoMVczQl5"
weight = 2

[[main]]
name = "Dulcimers"
pageRef = "dulcimers"
identifier = "dulcimers"
url = "/instruments/dulcimers"
parent = "WaoMVczQl5"
weight = 3

[[main]]
name = "Hand Pans"
pageRef = "handpans"
identifier = "handpans"
url = "/instruments/handpans"
parent = "WaoMVczQl5"
weight = 4

[[main]]
name = "World"
pageRef = "world"
identifier = "world"
url = "/instruments/world"
parent = "WaoMVczQl5"
weight = 5

[[main]]
name = "Ukuleles"
pageRef = "ukuleles"
identifier = "ukuleles"
url = "/instruments/ukuleles"
parent = "WaoMVczQl5"
weight = 6

[[main]]
name = "Diddley Bows"
pageRef = "diddleybows"
identifier = "diddleybows"
url = "/instruments/diddleybows"
parent = "WaoMVczQl5"
weight = 7

[[main]]
name = "Canjos"
pageRef = "canjos"
identifier = "canjos"
url = "/instruments/canjos"
parent = "WaoMVczQl5"
weight = 8

[[main]]
name = "Harps"
pageRef = "harps"
identifier = "harps"
url = "/instruments/harps"
parent = "WaoMVczQl5"
weight = 9


###### Gear ######

[[main]]
name = "Gear"
pageRef = "gear"
url = "/gear"
identifier = "kNkZxyimtI"
weight = 2

[[main]]
name = "Amps"
pageRef = "amps"
identifier = "amps"
url = "/gear/amps"
parent = "kNkZxyimtI"
weight = 1

[[main]]
name = "Pedals"
pageRef = "pedals"
identifier = "pedals"
url = "/gear/pedals"
parent = "kNkZxyimtI"
weight = 2

[[main]]
name = "Mics"
pageRef = "mics"
identifier = "mics"
url = "/gear/mics"
parent = "kNkZxyimtI"
weight = 3

[[main]]
name = "Slides"
pageRef = "slides"
identifier = "slides"
url = "/gear/slides"
parent = "kNkZxyimtI"
weight = 4

[[main]]
name = "Speakers"
pageRef = "speakers"
identifier = "speakers"
url = "/gear/speakers"
parent = "kNkZxyimtI"
weight = 5


###### Other Projects ######

[[main]]
name = "Other Projects"
pageRef = "otherprojects"
url = "/otherprojects/"
identifier = "3yV9yfPrBj"
weight = 3

###### Footer ######

[[footer]]
none = "none"

[[footer]]
name = "Home"
pageRef = ""
identifier = "b0M0hadtTb"
weight = 9999
