baseURL = 'https://alexllama.github.io/'
#baseURL = 'https://stringsandtines.com/'
languageCode = 'en-us'
title = 'Strings and Tines'
theme = 'blowfish'

# Required for the Blowfish theme
enableRobotsTXT = true

[pagination]
  pagerSize = 20

summaryLength = 30

[params]
  # (Optional) If you're using Google Analytics, add your tracking ID here
  googleAnalytics = ""
  mainSections = ["Instruments", "MiscInstruments", "Gear", "Electronics", "Photography"]
  description = "A collection of my instruments, musical creations, electronics tinkering and other projects."

[markup.highlight]
  noClasses = false

# Ignore specific Hugo warnings
[logging]
  ignoreLogs = ['warning-partial-superfluous-prefix']

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Instruments"
    url = "/Instruments/"
    weight = 20
  [[menu.main]]
    name = "Gear"
    url = "/Gear/"
    weight = 30
  [[menu.main]]
    name = "Misc Instruments"
    url = "/MiscInstruments/" 
    weight = 40
  [[menu.main]]
    name = "Electronics"
    url = "/Electronics/"
    weight = 50
  [[menu.main]]
    name = "Photography"
    url = "/Photography/"
    weight = 60
  